# إعدادات توجيه SPA لمنع ظهور صفحة 404 عند تحديث الصفحة أو الدخول المباشر للرابط
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# إعدادات لضغط الملفات وسرعة الموقع
[build]
  publish = "."
