name: Compile Tailwind CSS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Tailwind CSS
        run: npm install -D tailwindcss

      - name: Build CSS
        run: npx tailwindcss -i ./src/input.css -o ./css/style.css --minify

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add css/style.css
          git commit -m "Auto: Compile and Minify Tailwind CSS" || echo "No changes to commit"
          git push
